### ISSUE TITLE
Use intx instead of boost::multiprecision in aleth-interpreter

### ISSUE THREAD

**Issue by chfast** [ethereum/aleth#5720] opened 2019-08-20 10:41 UTC
Replace `boost::multiprecision` in aleth-interpreter with [intx](https://github.com/chfast/intx) library and measure the performance difference with `evmone-bench` tool.

**Comment by theStack** [comment] 2019-09-20 00:08
I'd be interested to work on this. After having a first look into aleth-interpreter: since the currently used type `u256` is defined and used outside, in `libdevcore/Common.h`, I guess the type has to replaced in *every* module using `u256`?
Or is the idea to use `intx` just for the really performance intensive opcodes in libaleth-interpreter as a first step, keeping `boost::multiprecision` for the rest and just convert back and forth?

**Comment by chfast** [comment] 2019-09-20 08:58
Hi @theStack,

The task is about replacing `u256` by `intx::uint256` only in aleth-interpreter library. Although that may not be obviously visible, this library is well separated from other parts of the Aleth project. The conversions from boost to intx (and the opposite direction) should not be needed in the end.

You can start by changing the VM stack https://github.com/ethereum/aleth/blob/master/libaleth-interpreter/VM.h#L102
from `u256 m_stack[VMSchedule::stackLimit]` to `intx::uint256 m_stack[VMSchedule::stackLimit]`.

You can use evmone as an example how to convert uint256 from/to addresses and hashes:
- https://github.com/ethereum/evmone/blob/master/lib/evmone/instructions.cpp#L322
- https://github.com/ethereum/evmone/blob/master/lib/evmone/instructions.cpp#L329

**Comment by theStack** [comment] 2019-09-20 12:08
@chfast Thanks for the explanation, glad to hear that the library is well separated, considering this the task sounds to be doable in a finite amount of time ;-)
Right now though I fail already on adding intx to the build process via Hunter. After adding the following two lines on the top of `libaleth-interpreter/CMakeLists.txt`:

```
hunter_add_package(intx)
find_package(intx CONFIG REQUIRED)
```

executing `cmake ..` from the (empty) build directory leads to quite some errors:
```
-- [hunter] Building intx
loading initial cache file /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/cache.cmake
loading initial cache file /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/args.cmake
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Build
Scanning dependencies of target intx-Release
[ 12%] Creating directories for 'intx-Release'
[ 25%] Performing download step (download, verify and extract) for 'intx-Release'
-- verifying file...
       file='/home/honey/.hunter/_Base/Download/intx/0.2.0/50c4d8e/v0.2.0.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/honey/.hunter/_Base/Download/intx/0.2.0/50c4d8e/v0.2.0.tar.gz'
  SHA1='50c4d8ec601114755be9fd5bf5b288ee4eeacd54'
-- extracting...
     src='/home/honey/.hunter/_Base/Download/intx/0.2.0/50c4d8e/v0.2.0.tar.gz'
     dst='/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'intx-Release'
[ 50%] No update step for 'intx-Release'
[ 62%] Performing configure step for 'intx-Release'
loading initial cache file /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/cache.cmake
loading initial cache file /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/args.cmake
-- [cable ] Cable 0.4.0 initialized
-- [cable ] Build type: Release
-- The CXX compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test fstack-protector
-- Performing Test fstack-protector - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- Performing Test mtune=generic
-- Performing Test mtune=generic - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Build/intx-Release-prefix/src/intx-Release-build
[ 75%] Performing build step for 'intx-Release'
Scanning dependencies of target intx
[ 50%] Building CXX object lib/intx/CMakeFiles/intx.dir/div.cpp.o
In file included from /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/lib/intx/div.cpp:5:
In file included from /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/lib/intx/div.hpp:7:
In file included from /home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/intx.hpp:7:
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:76:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto lo = x.lo + y.lo;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:77:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto carry = x.lo > lo;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:78:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto hi = x.hi + y.hi + carry;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:89:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto lo = x.lo - y.lo;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:90:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto borrow = x.lo < lo;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:91:16: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    const auto hi = x.hi - y.hi - borrow;
               ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:234:5: error: use of this statement in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    if (shift < 128)
    ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:236:5: error: multiple return statements in constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    return 0;
    ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:235:9: note: previous return statement is here
        return x << unsigned(shift);
        ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:253:5: error: use of this statement in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    if (shift < 128)
    ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:255:5: error: multiple return statements in constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    return 0;
    ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:254:9: note: previous return statement is here
        return x >> unsigned(shift);
        ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:268:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t xl = x & 0xffffffff;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:269:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t xh = x >> 32;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:270:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t yl = y & 0xffffffff;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:271:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t yh = y >> 32;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:273:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t t0 = xl * yl;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:274:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t t1 = xh * yl;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:275:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t t2 = xl * yh;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:276:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t t3 = xh * yh;
             ^
/home/honey/.hunter/_Base/c022f0c/88b7a57/6d1bd54/Build/intx/Source/include/intx/int128.hpp:278:14: error: variable declaration in a constexpr function is a C++14 extension [-Werror,-Wc++14-extensions]
    uint64_t u1 = t1 + (t0 >> 32);
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

Seems to be an C++ standard issue? How can I select the proper one? 
Changing `cable_configure_toolchain(DEFAULT cxx11-pic)` to `cable_configure_toolchain(DEFAULT cxx14-pic)` in `aleth/CMakeLists.txt` didn't help either.

By the way, I'm not sure if this is the right place to ask questions like this, but I could imagine someone else working on this could stumble on the same troubles, though.

**Comment by chfast** [comment] 2019-09-20 12:36
You may need to clear you build dir after changing the toolchain. Or try `-DTOOLCHAIN=cxx14-pic` cmake option.

**Comment by theStack** [comment] 2019-09-20 13:19
> 
> 
> You may need to clear you build dir after changing the toolchain. Or try `-DTOOLCHAIN=cxx14-pic` cmake option.

Tried both, still no success. I will look more into detail what is the difference between the cmake config in evmone and aleth (regarding the including of intx via Hunter) , since it *does* build just fine in evmone. With a verbose cmake output the cause of the problem should be found in the end.

**Comment by theStack** [comment] 2019-09-21 00:09
It seems that I accidentially called `cmake` on the main directory rather on the separate `build` directory before. Removing all this and just changing `cable_configure_toolchain(DEFAULT cxx11-pic)` to `cable_configure_toolchain(DEFAULT cxx14-pic)` in `aleth/CMakeLists.txt` worked. So let the fun begin...

**Comment by theStack** [comment] 2019-09-22 11:13
@chfast: The replacement is practically done, and the benchmarked results look good, with a speedup of at least 100% (`Run on (8 X 1917.61 MHz CPU s)`), here an excerpt for the `weierstrudel` benchmarks:

| Benchmark | using boost::multiprecision | using intx |
| --- | --- | --- |
| weierstrudel/0 | 1916us | 796us |
| weierstrudel/1 | 3903us | 1725us | 
| weierstrudel/3 | 5773us | 2514us |
| weierstrudel/9 | 12188us | 5449us |
| weierstrudel/14 | 18517s | 8031us | 

Before I push my changes though, I want to get sure that they don't break anything, so my questions would be:

1. How to test for the correctness of a EVM instance? I found there is a tool `evm-test` in the evmone repository as well. Is it enough if this tool passes or is there any other tools to test correctness?
2. Is there any specific benchmarks you'd like to see tested? I just used the one shipped with evmone, are there any other around, e.g. making heavy use of exponentiation, addmod, mulmod etc.?
3. Is it okay to lift the used C++ standard for the whole aleth project from C++11 to C++14 (like I do it now) just because of intx, or should there be put extra effort to e.g. just use C++14 for libaleth-interpreter?

By the way, in the end I encoutered only one place where a conversion to `boost::multiprecision` is necessary, which is for the exception `throwBufferOverrun()` which expects a `bigint` as argument.

**Comment by chfast** [comment] 2019-09-23 10:55
@theStack that's sound awesome. I didn't expect this to happen so quickly.

1. The aleth-interpreter is tested on CI, so you can push your code any time. To test it locally, run `testeth -- --vm interpreter`. Using `evm-test` from evmone would be additional check.

2. Using the beckmarks from evmone is good enough. I'm mostly interested in relative performance gain between aleth-interpreter/boost and aleth-interpreter/intx. Another set of benchmarks is https://github.com/gcolvin/evm-drag-race - I was considering importing them to evmone, but this is not done yet.

3. I think we are at the point that we can migrate whole Aleth project to C++14 or even C++17. That was planned for a long time, but I need to check if everything is ready.

4. About the `throwBufferOverrun()` issue: using exceptions there is not ideal but this was inherited from the "legacy" vm. Anyway, to workaround the issue you can create a new exception type. They do not need to be shared. I expect the bigint value there is probably discarded anyway when converting to EVMC status code.

**Comment by theStack** [comment] 2019-09-23 14:12
>1. The aleth-interpreter is tested on CI, so you can push your code any time. To test it locally, run `testeth -- --vm interpreter`. Using `evm-test` from evmone would be additional check.

Right, here we go: https://github.com/ethereum/aleth/pull/5757
Note that for the ops `SLT` and `SGT` I used the same method with testing for the MSB as in evmone, to avoid converting to signed types (which, as I see it, don't exist int intx).

>2. Using the beckmarks from evmone is good enough. I'm mostly interested in relative performance gain between aleth-interpreter/boost and aleth-interpreter/intx. Another set of benchmarks is https://github.com/gcolvin/evm-drag-race - I was considering importing them to evmone, but this is not done yet.

Good, I will present the full table of the evmone-table benchmark results here as well soon.

>3. I think we are at the point that we can migrate whole Aleth project to C++14 or even C++17. That was planned for a long time, but I need to check if everything is ready.

Okay, in the first of my commits it is set to C++14 (in the global `CMakeLists.txt`) as this was obviously the minimum needed version for intx.

>4. About the `throwBufferOverrun()` issue: using exceptions there is not ideal but this was inherited from the "legacy" vm. Anyway, to workaround the issue you can create a new exception type. They do not need to be shared. I expect the bigint value there is probably discarded anyway when converting to EVMC status code.

I solved this simply by converting the intx type to a hexstring (via `intx::hex()`) and then constructing a bigint type with that string again -- a bit clumsy and not performant, but well, it's only an exception anyway and like you said, its probably better to create a new exception type in the future. If I understood it correctly the bigint is needed here because it contains the result of adding two u256 integers (memory address + offset), passing the address which is out of range to the exception.

**Comment by theStack** [comment] 2019-09-23 16:59
Here are the full benchmark results for the set included in evmone (see https://gist.github.com/theStack/8cf5baed217994011cbbce0d775c9d67 for the detailled benchmark runs output):

| Benchmark | using boost::multiprecision | using intx | speedup |
| --- | --- | --- | --- |
| blake2b_huff/analysis | 65us | 55us | x1,18 |
| blake2b_huff/empty | 931us | 205us | x4,5 | 
| blake2b_huff/2805nulls | 16183us | 2216us | x7,3 |
| blake2b_huff/5610nulls | 12188us | 5449us | x2,2 |
| blake2b_huff/8415nulls | 18517s | 8031us | x2,3 |
| blake2b_huff/65536nulls | 377451us | 41595us | x9 |
| blake2b_shifts/analysis | 30us | 30us | (x1) |
| blake2b_shifts/2805nulls | 56145us | 15321us | x3,6 |
| blake2b_shifts/5610nulls | 117242us | 29947us | x3,9 |
| blake2b_shifts/8415nulls | 175517us | 46137us | x3,8 |
| sha1_divs/analysis | 7us | 6us | x1,16 |
| sha1_divs/empty | 644 us | 234us | x2,75 |
| sha1_divs/1351 | 11635us | 4378us | x2,65 |
| sha1_divs/2737 | 22952us | 8447us | x2,7 |
| sha1_divs/5311 | 41099us | 16351us | x2,5 |
| sha1_divs/65536 | 474640us | 202271us | x2,34 |
| sha1_shifts/analysis | 5us | 5us | (x1) |
| sha1_shifts/empty | 427us | 188us | x2,27 |
| sha1_shifts/1351 | 7643us | 3624us | x2,1 |
| sha1_shifts/2737 | 14781us | 7056us | x2,09 |
| sha1_shifts/5311 | 29017us | 13780us | x2,1 |
| sha1_shifts/65536 | 348345us | 168569us | x2,06 |
| weierstrudel/analysis | 68us | 67us | x1,01 |
| weierstrudel/0 | 1858us | 624us | x2,9 |
| weierstrudel/1 | 3710us | 1275us | x2,9 |
| weierstrudel/3 | 6129us | 1923us | x3,18 |
| weierstrudel/9 | 13560us | 3901us | x3,47 |
| weierstrudel/14 | 19261us | 5509us | x3,49 |
| micro/loop_with_many_jumpdests/analysis | 547us | 554us | x0,98 |
| micro/loop_with_many_jumpdests | 45029us | 41345us | x1,08 |

**Comment by theStack** [comment] 2019-10-07 14:33
This issue can be closed now as the pull request https://github.com/ethereum/aleth/pull/5757 has been merged into master.

**Closed** 2019-10-07 15:23 UTC
Labels: help wanted
