### ISSUE TITLE
m_evictions usage 

### ISSUE THREAD

**Issue by lyy4j** [ethereum/aleth#5374] opened 2018-12-01 13:53 UTC
I  hava the doubt when I read the code 【if (e->second.evictedTimePoint > std::chrono::steady_clock::now())】，it will return false forever?

**Comment by lyy4j** [comment] 2018-12-01 14:05
@chfast  ,Could you do me a favour to have a look and tell me why?

**Comment by gumb0** [comment] 2018-12-11 13:30
Duplicate of https://github.com/ethereum/aleth/issues/4507

**Closed by gumb0** 2018-12-11 13:30 UTC
