### ISSUE TITLE
Build Failed when building from source on Win 10 64 fails. 

### ISSUE THREAD

**Issue by VERTlG0** [ethereum/aleth#4524] opened 2017-09-20 01:42 UTC
```sh
C:\Crypto\ethereum\cpp-ethereum>scripts\install_deps.bat
Downloading leveldb-1.2.tar.gz
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
Unpacking leveldb-1.2.tar.gz to C:/Crypto/ethereum/cpp-ethereum/deps
Downloading microhttpd-0.9.2.tar.gz
-- [download 0% complete]
-- [download 3% complete]
-- [download 6% complete]
-- [download 9% complete]
-- [download 12% complete]
-- [download 15% complete]
-- [download 18% complete]
-- [download 21% complete]
-- [download 24% complete]
-- [download 27% complete]
-- [download 30% complete]
-- [download 33% complete]
-- [download 36% complete]
-- [download 39% complete]
-- [download 42% complete]
-- [download 45% complete]
-- [download 48% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 86% complete]
-- [download 89% complete]
-- [download 92% complete]
-- [download 95% complete]
-- [download 98% complete]
-- [download 100% complete]
Unpacking microhttpd-0.9.2.tar.gz to C:/Crypto/ethereum/cpp-ethereum/deps

C:\Crypto\ethereum\cpp-ethereum>mkdir build

C:\Crypto\ethereum\cpp-ethereum>cd build

C:\Crypto\ethereum\cpp-ethereum\build>cmake -G "Visual Studio 15 2017 Win64" ..
-- [hunter] Initializing Hunter workspace (8fe144d9490501d398777532e0c0f56bc7bb0ec7)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.19.71.tar.gz
-- [hunter]   -> C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d
-- The C compiler identification is MSVC 19.11.25507.1
-- The CXX compiler identification is MSVC 19.11.25507.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: C:/Users/Vertigo/.hunter
-- [hunter] [ Hunter-ID: 8fe144d | Toolchain-ID: d998d32 | Config-ID: 3fd9419 ]
-- [hunter] BOOST_ROOT: C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Install (ver.: 1.64.0)
-- [hunter] Building Boost
loading initial cache file C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/cache.cmake
loading initial cache file C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/args.cmake
-- The C compiler identification is MSVC 19.11.25507.1
-- The CXX compiler identification is MSVC 19.11.25507.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1954 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "x" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2565 (_ep_add_download_command)
  CMakeLists.txt:129 (ExternalProject_Add)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1400 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "x" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1593 (_ep_write_log_script)
  C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2040 (ExternalProject_Add_Step)
  C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2565 (_ep_add_download_command)
  CMakeLists.txt:129 (ExternalProject_Add)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/19/2017 6:13:16 PM.
Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ALL_BUILD.vcxproj" (1) is building "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ZERO_CHECK.vcxproj" (default targets).
Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ALL_BUILD.vcxproj" (1) is building "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\Boost\".
  Creating directory "x64\Debug\Boost\Boost.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\Boost\Boost.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost-prefix\src\Boost-stamp\Debug\".
  Creating directory "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\CMakeFiles\Debug\".
CustomBuild:
  Building Custom Rule C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/CMakeLists.txt
  CMake does not need to re-run because C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/CMakeFiles/generate.stamp is up-to-date.
  Creating directories for 'Boost'
  Performing download step (download, verify and extract) for 'Boost'
  -- Boost download command succeeded.  See also C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log
  No update step for 'Boost'
  No patch step for 'Boost'
  Performing configure step for 'Boost'
  -- Boost configure command succeeded.  See also C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log
  No build step for 'Boost'
  Performing install step for 'Boost'
  CMake Error at C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
    Command failed: 1

     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'

    See also

      C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost.vcxproj]
Done Building Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\Vertigo\.hunter\_Base\8fe144d\d998d32\3fd9419\Build\Boost\Build\Boost.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:03:22.12

[hunter ** FATAL ERROR **] Build step failed (dir: C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/projects/Boost/hunter.cmake:259 (hunter_download)
  C:/Users/Vertigo/.hunter/_Base/Download/Hunter/0.19.71/8fe144d/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:96 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "C:/Crypto/ethereum/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
```

**Comment by VERTlG0** [comment] 2017-09-20 22:10
**Boost-install-err.log**

CMake Error at C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message):
  Command failed (The system cannot find the file specified):

   'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-coroutine2' '--without-date_time' '--without-exception' '--without-fiber' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/Users/Vertigo/.hunter/_Base/8fe144d/d998d32/3fd9419/Build/Boost/Install' '--ignore-site-config'

**Comment by gumb0** [comment] 2017-09-21 07:59
@chfast Can you help with this?

**Comment by chfast** [comment] 2017-09-21 08:51
1. Can you also send me `Boost-configure-*.log` log?
2. It will be hard to know what's going on without trying myself.
3. Is this related <https://github.com/ruslo/hunter/issues/745>?
4. The most important: You will not be able to build cpp-ethereum with VS 2017 yet. The scripts downloads pre-built leveldb and microhttpd libraries for VS 2015. They are not compatible with VS 2017. Someone would have to build them for VS 2017 or package them for Hunter.

**Comment by chfast** [comment] 2017-09-21 14:42
I can reproduce the Boost build error...

**Comment by antonmok** [comment] 2017-11-27 05:40
I can reproduce it as well.

cmake .. -G "Visual Studio 14 2015 Win64"

...

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/b96750b/1ed9955/59ec5bb/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/projects/Boost/hunter.cmake:272 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:101 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "D:/Projects/HaloPlatform/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
See also "D:/Projects/HaloPlatform/cpp-ethereum/build/CMakeFiles/CMakeError.log".

Windows 8.1 x64
VS2015 and 2017 installed.

**Comment by antonmok** [comment] 2017-11-27 06:16
This error gone when I uninstall CMake 3.9.1 which was installed before and install CMake 3.7.1

**Comment by chfast** [comment] 2017-11-29 13:38
Can you report your CMake version?

**Comment by glomarch** [comment] 2018-06-16 19:08
I have the same error
C:\Users\glomarch>cmake --version
cmake version 3.11.1

CMake suite maintained and supported by Kitware (kitware.com/cmake)

**Comment by halfalicious** [comment] 2018-11-06 06:33
I think we can close this since this is very old and I've been able to successfully build on Windows for quite some time. @chfast : What do you think?

**Closed** 2018-11-07 12:57 UTC
Labels: build
